In [1]:
import sys
sys.path.append('e:\\pytorch-models\\pytorch-multiGPU-template\\')
import torch
from util.datasets import build_dataset

import models

d:\miniconda\envs\lzm\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
dataset_val = build_dataset(False, None)

In [3]:
dataset_val

Dataset MNIST
    Number of datapoints: 10000
    Root location: e:\pytorch-models\pytorch-multiGPU-template\data\minist\val
    Split: Test
    StandardTransform
Transform: ToTensor()

In [4]:
from torch.utils.data.dataloader import DataLoader
loader = DataLoader(dataset_val, 2)

In [5]:
for batch in loader:
    print(batch[0])
    print(batch[0].shape)
    print(batch[1])
    print(batch[1].shape)
    break

tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]]])
torch.Size([2, 1, 28, 28])
tensor([7, 2])
torch.Size([2])


In [6]:
model = models.__dict__['MyModel_versionID']()

{}


In [7]:
model.forward(batch[0])

torch.Size([2, 784])
torch.Size([2, 512])
torch.Size([2, 256])
torch.Size([2, 64])


tensor([[-0.1550,  0.0266, -0.0025, -0.1715, -0.0445, -0.2376,  0.0555,  0.3663,
         -0.1590, -0.3324],
        [-0.1235, -0.0666,  0.0650, -0.1020, -0.3579,  0.1125,  0.1232,  0.0790,
         -0.1032, -0.0683]], grad_fn=<AddmmBackward0>)